name: Pipeline de Build e Teste com Docker Compose

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Rename compose files
        run: |
          mv Docker-compose.yml docker-compose.yml
          mv docker-compose-test.yml docker-compose.test.yml

      - name: Build e execução dos testes
        run: |
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from backend

      - name: Exibir logs do backend
        if: always()
        run: |
          docker compose -f docker-compose.test.yml logs backend

      - name: Limpeza dos recursos do Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v
