name: Docker Compose Build

on:
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run docker-compose
        run: |
          cd backend
          docker-compose -f docker-compose.yml up -d --build
          docker-compose ps

      - name: Run tests
        run: |
          cd backend
          docker-compose exec -T backend ./mvn test

      - name: Shutdown
        if: always()
        run: |
          cd backend
          docker-compose down
