name: Pipeline de Build e Teste com Docker Compose

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Build e execução dos testes
        run: |
          docker compose up --abort-on-container-exit --exit-code-from backend

      - name: Exibir logs do backend
        if: always()
        run: |
          docker compose logs backend

      - name: Limpeza dos recursos do Docker Compose
        if: always()
        run: |
          docker compose down -v
